apiVersion: v1
kind: Service
metadata: 
  name: taskifyapp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: taskifyapp
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30080
