# ---- Build React app ----
FROM node:18 AS build
WORKDIR /app
COPY . .              # Copy everything (since React code is in current folder)
RUN npm install
RUN npm run build

# ---- Serve React app using Nginx ----
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
