pipeline {
    agent any

    environment {
        IMAGE_NAME = 'taskify-react'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Itachijb93/taskify-app.git'
            }
        }

        stage('Build React App') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -f Dockerfile.react -t taskify-react .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 3000:80 --name react-app taskify-react'
            }
        }
    }
}
