pipeline {
    agent any

    environment {
        IMAGE_NAME = "taskify-react-app"
        CONTAINER_NAME = "taskify-react-container"
        BUILD_DIR = "client"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Itachijb93/taskify-app.git'
            }
        }

        stage('Install Dependencies and Build React App') {
            steps {
                dir("${BUILD_DIR}") {
                    sh 'node -v'
                    sh 'npm -v'
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                    docker rm -f $CONTAINER_NAME || true
                    docker run -d --name $CONTAINER_NAME -p 80:80 $IMAGE_NAME
                '''
            }
        }
    }

    post {
        failure {
            echo '❌ Build failed! Check logs above.'
        }
        success {
            echo '✅ Build and deployment completed successfully!'
        }
    }
}
